import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BadgeCheck, CarFront, Headphones, Leaf, MapPin, Route, Search, Send, ShieldCheck, Sparkles, Users } from "lucide-react";
import MotionShell from "@/components/MotionShell";
import TripSearch from "@/components/TripSearch";
import TravelCard from "@/components/TravelCard";
import { business, destinations, packages } from "@/lib/data";

export default function HomePage(){
  return <MotionShell><main>
    <section className="hero relative isolate min-h-[640px] overflow-hidden bg-[#08263f]">
      <div className="absolute inset-0 hero-image"><Image src="https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=2600&q=94" alt="Karnataka mountain travel inspiration" fill priority className="object-cover" sizes="100vw" quality={94}/></div>
      <div className="absolute inset-0 hero-gradient"/>
      <div className="container relative flex min-h-[640px] items-center py-24">
        <div className="hero-copy max-w-2xl text-white">
          <span className="mb-5 inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-4 py-2 text-xs font-medium text-teal-100 glass"><Sparkles size={14}/> Explore. Dream. Discover.</span>
          <h1 className="max-w-xl text-5xl font-semibold leading-[.98] tracking-[-.04em] md:text-7xl"><span className="inline-block overflow-hidden"><span className="hero-word inline-block">Explore</span></span>{" "}<span className="inline-block overflow-hidden"><span className="hero-word inline-block">Karnataka</span></span><br/><span className="inline-block overflow-hidden"><span className="hero-word inline-block">With</span></span>{" "}<span className="inline-block overflow-hidden"><span className="hero-word inline-block">Us</span></span></h1>
          <p className="hero-copy mt-6 max-w-xl text-base leading-7 text-white/80 md:text-lg">Local tours, flexible road trips and dependable vehicle rental from Bhadravathi. We shape practical journeys around your dates, people and pace.</p>
          <div className="hero-copy mt-8 flex flex-wrap gap-3"><Link href="/tours" className="magnetic inline-flex items-center gap-3 rounded-full bg-[#10a89e] px-6 py-3.5 text-sm font-semibold text-white shadow-lg shadow-black/10 transition hover:bg-[#087c76]">Discover Tours <span className="grid h-7 w-7 place-items-center rounded-full bg-white/15"><ArrowRight size={15}/></span></Link><Link href="/quote" className="magnetic inline-flex items-center rounded-full border border-white/30 bg-white/10 px-6 py-3.5 text-sm font-semibold text-white glass transition hover:bg-white/15">Plan My Trip</Link></div>
        </div>
      </div>
      <div className="container absolute inset-x-0 bottom-0 z-10 translate-y-1/2"><TripSearch/></div>
    </section>

    <section className="border-b border-slate-100 bg-white pt-24"><div className="container grid gap-6 py-9 md:grid-cols-4">
      {[["Local Expertise", "Bhadravathi-first service and practical regional routes", BadgeCheck],["Vehicle Options","Sedans, SUVs and group travel options",CarFront],["Flexible Itineraries","Routes built around your schedule",Route],["Helpful Support","One point of contact before and during travel",Headphones]].map(([t,d,I])=><div key={String(t)} className="scroll-reveal flex gap-4 border-r border-slate-100 pr-5 last:border-0"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#10a89e]/10 text-[#10a89e]"><I size={21}/></span><div><strong className="text-sm text-[#08263f]">{t}</strong><p className="mt-1 text-xs leading-5 text-slate-500">{d}</p></div></div>)}
    </div></section>

    <section className="py-20 md:py-24"><div className="container">
      <div className="scroll-reveal mb-10 flex items-end justify-between gap-6"><div><div className="text-[10px] font-semibold uppercase tracking-[.22em] text-[#10a89e]">Popular Destinations</div><h2 className="mt-2 text-3xl font-semibold tracking-tight text-[#08263f] md:text-4xl">Explore Top Destinations</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Start local, then build your route across Karnataka.</p></div><Link href="/destinations" className="hidden items-center gap-2 text-sm font-semibold text-[#10a89e] sm:flex">View all destinations <ArrowRight size={16}/></Link></div>
      <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{destinations.slice(0,6).map(item=><div className="scroll-reveal" key={item.slug}><TravelCard item={item}/></div>)}</div>
    </div></section>

    <section className="bg-[#f6faf9] py-20 md:py-24"><div className="container grid gap-10 lg:grid-cols-[.85fr_1.15fr] lg:items-center">
      <div className="scroll-reveal"><div className="text-[10px] font-semibold uppercase tracking-[.22em] text-[#10a89e]">Why travel with us</div><h2 className="mt-3 text-4xl font-semibold leading-tight tracking-tight text-[#08263f]">Making Travel<br/>Simple & Memorable</h2><p className="mt-5 max-w-lg text-sm leading-7 text-slate-600">We handle the practical details so you can focus on the journey. Ask for a private route, family plan, group vehicle or a fully custom Karnataka itinerary.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/about" className="magnetic inline-flex items-center gap-2 rounded-full bg-[#10a89e] px-5 py-3 text-sm font-semibold text-white">Learn More <ArrowRight size={15}/></Link><Link href="/booking" className="magnetic inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-5 py-3 text-sm font-semibold text-[#08263f]">Request Booking</Link></div><div className="mt-10 flex gap-9"><div><div className="text-3xl font-semibold text-[#08263f]"><span className="count-up" data-target="5">0</span>.0</div><span className="text-xs text-slate-500">Google rating</span></div><div><div className="text-3xl font-semibold text-[#08263f]"><span className="count-up" data-target={business.reviewCount}>0</span>+</div><span className="text-xs text-slate-500">Google reviews</span></div></div></div>
      <div className="grid gap-4 sm:grid-cols-2">{[[Users,"Customizable Trips","Personalized routes, stays and vehicle choices."],[Sparkles,"Diverse Experiences","Nature, heritage, hills, coast and city escapes."],[Leaf,"Comfort First","Clear choices, simple planning and responsive support."],[ShieldCheck,"Seamless Booking","Quote, confirm and manage in a few clear steps."]].map(([I,t,d])=><div key={String(t)} className="scroll-reveal card-tilt rounded-2xl border border-white bg-white p-7 soft-shadow"><I size={26} className="text-[#10a89e]"/><h3 className="mt-5 font-semibold text-[#08263f]">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{d}</p></div>)}</div>
    </div></section>

    <section className="py-20"><div className="container"><div className="scroll-reveal relative overflow-hidden rounded-3xl bg-[#08263f] p-8 text-white md:p-12">
      <Image src="https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=2200&q=92" alt="Scenic travel offer background" fill className="object-cover opacity-35" quality={92}/><div className="absolute inset-0 bg-gradient-to-r from-[#08263f]/95 via-[#08263f]/70 to-transparent"/><div className="relative grid gap-9 lg:grid-cols-[1.1fr_1fr] lg:items-center"><div><div className="text-[10px] font-semibold uppercase tracking-[.22em] text-teal-200">Special Offer</div><h2 className="mt-3 text-3xl font-semibold md:text-4xl">Plan Your Next Karnataka Escape</h2><p className="mt-3 max-w-xl text-sm leading-6 text-white/75">Combine local sightseeing, vehicle rental and group travel into one simple plan.</p><Link href="/quote" className="magnetic mt-6 inline-flex items-center gap-2 rounded-full bg-[#10a89e] px-5 py-3 text-sm font-semibold text-white">Get My Quote <ArrowRight size={15}/></Link></div><div className="grid gap-3 sm:grid-cols-3">{[[Users,"Group Friendly"],[BadgeCheck,"Flexible Plans"],[Route,"Route Based"]].map(([I,t])=><div key={String(t)} className="rounded-2xl border border-white/10 bg-white/10 p-5 glass"><I size={20} className="text-teal-200"/><strong className="mt-4 block text-sm">{t}</strong><span className="mt-1 block text-xs leading-5 text-white/65">Built around real travel needs.</span></div>)}</div></div>
    </div></div></section>

    <section className="pb-20"><div className="container grid items-center gap-6 rounded-2xl border border-slate-100 bg-[#f5faf9] p-6 md:grid-cols-[.9fr_1.1fr] md:p-8"><div className="scroll-reveal flex items-center gap-4"><span className="grid h-12 w-12 place-items-center rounded-full bg-white text-[#10a89e] soft-shadow"><Send size={21}/></span><div><strong className="block text-base text-[#08263f]">Get Travel Inspiration</strong><span className="text-sm text-slate-500">Occasional travel ideas and useful planning tips.</span></div></div><form className="flex flex-col gap-2 sm:flex-row" action="/contact"><input required type="email" name="email" placeholder="Enter your email address" className="min-h-12 flex-1 rounded-full border border-slate-200 bg-white px-5 text-sm outline-none focus:border-[#10a89e]"/><button className="magnetic min-h-12 rounded-full bg-[#10a89e] px-6 text-sm font-semibold text-white transition hover:bg-[#087c76]" type="submit">Subscribe</button></form></div></section>

    <section className="pb-24"><div className="container overflow-hidden rounded-3xl border border-slate-100 bg-white soft-shadow"><div className="grid lg:grid-cols-2"><div className="relative min-h-[330px] overflow-hidden"><Image src="https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=1800&q=92" alt="Sri Kala Bhairava Holidays location" fill className="parallax-image object-cover" quality={92}/></div><div className="p-8 md:p-12"><div className="text-[10px] font-semibold uppercase tracking-[.22em] text-[#10a89e]">Visit / Directions</div><h2 className="mt-3 text-3xl font-semibold text-[#08263f]">Travel starts locally.</h2><p className="mt-4 text-sm leading-7 text-slate-500">{business.description}</p><div className="mt-6 flex gap-3"><div className="grid h-11 w-11 place-items-center rounded-full bg-[#10a89e]/10 text-[#10a89e]"><MapPin size={19}/></div><div><strong className="text-sm text-[#08263f]">{business.address}</strong><p className="mt-1 text-xs text-slate-500">{business.lat}, {business.lng}</p></div></div><div className="mt-7 flex flex-wrap gap-3"><a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/dir/?api=1&destination=${business.lat},${business.lng}`} className="magnetic inline-flex items-center gap-2 rounded-full bg-[#10a89e] px-5 py-3 text-sm font-semibold text-white">Get Directions <ArrowRight size={15}/></a><Link href="/contact" className="magnetic inline-flex items-center gap-2 rounded-full border border-slate-200 px-5 py-3 text-sm font-semibold text-[#08263f]">Contact Us</Link></div></div></div></div></section>
  </main></MotionShell>;
}